* org-html-barebones-fold

org-html-barebones-fold is a simplification of the incredible work of [[https://github.com/fniessen][fniessen]], particularly his ~hideshow.js~ from https://github.com/fniessen/org-html-themes.

Per a comissioned request, I have slimmed down the stylesheets, JS codebase, and adjusted some functionality to try to achieve a very simple HTML export setupfile for org-exported HTML.

It's a great canvas for future decoration and expansion, as the folding and unfolding functionality is fully implemented by ~hideshow.js~ (again by fniessen).

** Usage

See demo.org for usage. Boils down to including the CSS and JS files in the header of your exported HTML. Basic org mode export knowledge assumed. See a video I made for the basics of that if you're unsure: https://www.youtube.com/watch?v=8Gw4Y2EpcOY

* Contact

Please feel free to email (see GitHub profile) with questions or requests, or open an issue here on GitHub.

* License

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.

